[world]
name = "Athanor"
description = "Fully on-chain competitive grimoire race"
seed = "athanor-v0.0.3"

[namespace]
default = "ATHANOR"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
# world_address = "0x022eed2366c206971b6ab82b338721a5840098206c0eca529131de62c831d336"
account_address = "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753"
keystore_path = "./keystore_sepolia.json"

[writers]
"ATHANOR" = ["ATHANOR-Play"]

[owners]
"ATHANOR" = ["ATHANOR-Setup"]

[migration]
order_inits = ["ATHANOR-Play", "ATHANOR-Setup"]

[init_call_args]
"ATHANOR-Play" = [
  "0x0142712722e62a38f9c40fcc904610e1a14c70125876ecaaf25d803556734467",
  "0x1",
  "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f",
]
"ATHANOR-Setup" = []
