world_address = "0x033520e9a9f3d48f6c44f2604ff7805e65facf55f4880713f048fe9c217b6ba1"
rpc = "https://api.cartridge.gg/x/zathanor-slot/katana"

[indexing]
pending = true
transactions = true
namespaces = ["athanor_0_1"]
