world_address = "0x0562043d4e591762eec71ab33a67c1319ba8c61a53841c9cc4e9bbab8e7c7001"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[erc]
metadata_updates = true
