world_address = "0x77382f71a4459797905b267e6a2f6e395ce914f3942e2fe140ffa712b1a9e81"
rpc = "https://api.cartridge.gg/x/athanor-djizus-slot/katana"

[indexing]
pending = true
transactions = true
namespaces = ["athanor"]
