world_address = "0x2f7d2a01f4a8273a75d3c6b625a2a47469dbeac537afb38ada984e2b358b185"
rpc = "https://api.cartridge.gg/x/zathanor-slot/katana"

[indexing]
pending = true
transactions = true
namespaces = ["athanor_0_1"]
