world_address = "0x022eed2366c206971b6ab82b338721a5840098206c0eca529131de62c831d336"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[indexing]
world_block = 0
controllers = true
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

[erc]
metadata_updates = true
