import { defineComponent, Type as RecsType } from '@dojoengine/recs'
import { world } from './world'

export const contractComponents = {
  Game: defineComponent(
    world,
    {
      id: RecsType.BigInt,
      heroes: RecsType.Number,
      started_at: RecsType.BigInt,
      ended_at: RecsType.BigInt,
      remaining_tries: RecsType.Number,
      gold: RecsType.Number,
      hint_price: RecsType.Number,
      grimoire: RecsType.Number,
      hints: RecsType.Number,
      tries: RecsType.BigInt,
      ingredients: RecsType.BigInt,
      effects: RecsType.BigInt,
      seed: RecsType.BigInt,
    },
    { id: 'Game' },
  ),
  Character: defineComponent(
    world,
    {
      game_id: RecsType.BigInt,
      id: RecsType.Number,
      role: RecsType.Number,
      health: RecsType.Number,
      max_health: RecsType.Number,
      power: RecsType.Number,
      regen: RecsType.Number,
      gold: RecsType.Number,
      available_at: RecsType.BigInt,
      ingredients: RecsType.BigInt,
    },
    { id: 'Character' },
  ),
  Discovery: defineComponent(
    world,
    {
      game_id: RecsType.BigInt,
      ingredient_a: RecsType.Number,
      ingredient_b: RecsType.Number,
      effect: RecsType.Number,
      discovered: RecsType.Boolean,
    },
    { id: 'Discovery' },
  ),
  Hint: defineComponent(
    world,
    {
      game_id: RecsType.BigInt,
      ingredient: RecsType.Number,
      recipes: RecsType.Number,
    },
    { id: 'Hint' },
  ),
  GameSession: defineComponent(
    world,
    {
      game_id: RecsType.BigInt,
      player: RecsType.BigInt,
      seed: RecsType.BigInt,
      settings_id: RecsType.Number,
      discovered_count: RecsType.Number,
      failed_combo_count: RecsType.Number,
      craft_attempts: RecsType.Number,
      hints_used: RecsType.Number,
      gold: RecsType.Number,
      hero_count: RecsType.Number,
      potion_count: RecsType.Number,
      game_over: RecsType.Boolean,
      started_at: RecsType.BigInt,
    },
    { id: 'GameSession' },
  ),
  GameSeed: defineComponent(
    world,
    {
      game_id: RecsType.BigInt,
      seed: RecsType.BigInt,
    },
    { id: 'GameSeed' },
  ),
  GameSettings: defineComponent(
    world,
    {
      settings_id: RecsType.Number,
      zone_count: RecsType.Number,
      ingredients_per_zone: RecsType.Number,
      recipes_to_discover: RecsType.Number,
      max_heroes: RecsType.Number,
      hero_base_hp: RecsType.Number,
      hero_base_power: RecsType.Number,
      hero_base_regen: RecsType.Number,
      hint_base_cost: RecsType.Number,
      hint_cost_multiplier: RecsType.Number,
      soup_gold_value: RecsType.Number,
      progressive_cap: RecsType.Number,
    },
    { id: 'GameSettings' },
  ),
  GameSettingsMetadata: defineComponent(
    world,
    {
      settings_id: RecsType.Number,
      name: RecsType.BigInt,
      created_by: RecsType.BigInt,
      created_at: RecsType.BigInt,
      is_active: RecsType.Boolean,
    },
    { id: 'GameSettingsMetadata' },
  ),
  Config: defineComponent(
    world,
    {
      key: RecsType.BigInt,
      token_address: RecsType.BigInt,
      vrf_address: RecsType.BigInt,
    },
    { id: 'Config' },
  ),
}
